version: "3.9"

services:
  postgres:
    image: postgres:17.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    # next two lines are for checking how well dump.sql is imported
    # volumes:
    #   - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - ${PORT}
